### Word2Vec

#### Word2vec is feature extraction technique like bow and Tfidf but it is differ from it . it gives sementic meaning of words . If those words are in similar context then place those words close to each other in hight dimensional space
#### it has two types
#### 1.CBOW (Continous bag of words)
#### 2.Skipgram



##### 1.CBOW : Basically it predicts center or target word on basis of surrounding context word
##### 2.skipgram : skipgram takes cnter or target word on basis of it . it make prediction of surrounding words

### In this case study we just import the Googlenewsvector pre trained model (as a Dataset) and it trained with 100 billions of google news article words. it is trained on large dataset. in this model contain words(3 million) and vectors(numerical representation of vectors). we just check how itgive most similar words based on cosine similarity score and as well as  similarity() shows how much they are similar on basis of cosine similarity words . we are not building any model model from scratch here

#### Import basic libraries for word2vec

In [1]:
import gensim     # we import gensim and from gensim we import wordvec
from gensim.models import Word2Vec , KeyedVectors
#keyedvectors are class to handle or access word vectors efficiently
import numpy as np
import pandas as pd

##### We have to download the Google News prerained model. which is trained on google news article data over 100 billions of words from google news. for that reason wget will assist to download from internet to local system

#### This wget is no significance with NLp . it is like linux command

In [2]:
#!pip install wget

##### Here basically we donwload one dataset Googlenewsvectornegative300 . It contains 100 billion words of google news article basically this is pretrained model

#### Our data is in zip (mode) file so we need to unzip it so we will import zipfile
#### zipfile is package help to unzip file

In [3]:
import zipfile

In [4]:
data = zipfile.ZipFile('C:\\Users\\Lenovo\\Downloads\\archive(2).zip')

#### Here basically we open the zip file from this location . In zipfile module ZipFile is the function

In [5]:
data

<zipfile.ZipFile filename='C:\\Users\\Lenovo\\Downloads\\archive(2).zip' mode='r'>

In [6]:
data.extractall('C:\\Users\\Lenovo\\Downloads')

#### extract the data(compressed data of zip file) in download directory or at that address

In [7]:
data.close()

#### File get unzip and we close the zip file object . data is zip file object

#### Now our file is unzip so we can use extract file and import data in jupyter notebook 

In [8]:
#### For thats we use keyedVectors

In [11]:
model = KeyedVectors.load_word2vec_format('C:\\Users\\Lenovo\\Downloads\\GoogleNews-vectors-negative300.bin' , binary = True , limit = 500000)

In [12]:
model

#### Actually this pretrained model contains words(tokens) as well as vectors(embeding of words means or numerical representation of words). it contains 3 million words

#### We check some words from pre trained model . Basically this model is already get trained no need to build from scratch here

In [13]:
model['happy']

array([-5.18798828e-04,  1.60156250e-01,  1.60980225e-03,  2.53906250e-02,
        9.91210938e-02, -8.59375000e-02,  3.24218750e-01, -2.17285156e-02,
        1.34765625e-01,  1.10351562e-01, -1.04980469e-01, -2.90527344e-02,
       -2.38037109e-02, -4.02832031e-02, -3.68652344e-02,  2.32421875e-01,
        3.20312500e-01,  1.01074219e-01,  5.83496094e-02, -2.91824341e-04,
       -3.29589844e-02,  2.11914062e-01,  4.32128906e-02, -8.59375000e-02,
        2.81250000e-01, -1.78222656e-02,  3.79943848e-03, -1.71875000e-01,
        2.06054688e-01, -1.85546875e-01,  3.73535156e-02, -1.21459961e-02,
        2.04101562e-01, -3.80859375e-02,  3.61328125e-02, -8.15429688e-02,
        8.44726562e-02,  9.37500000e-02,  1.44531250e-01,  7.42187500e-02,
        2.51953125e-01, -7.91015625e-02,  8.69140625e-02,  1.58691406e-02,
        1.09375000e-01, -2.23632812e-01, -5.15747070e-03,  1.68945312e-01,
       -1.36718750e-01, -2.51464844e-02, -3.85742188e-02, -1.33056641e-02,
        1.38671875e-01,  

In [14]:
model['enjoy']

array([-1.25885010e-03, -4.83398438e-02, -2.83203125e-01,  3.24218750e-01,
        1.44653320e-02,  1.27929688e-01,  1.94335938e-01, -5.95703125e-02,
       -1.53320312e-01,  1.86523438e-01, -1.00097656e-01, -2.61718750e-01,
       -1.36718750e-02,  6.98242188e-02,  3.12500000e-02,  2.19726562e-01,
        1.60156250e-01,  1.64062500e-01,  2.85156250e-01, -4.24804688e-02,
       -1.42578125e-01,  1.91406250e-01,  8.98437500e-02,  1.82617188e-01,
        1.25976562e-01, -5.05371094e-02,  4.22363281e-02,  1.14257812e-01,
       -9.71679688e-02, -1.18652344e-01, -7.47070312e-02, -3.46679688e-02,
       -8.30078125e-02,  2.06054688e-01,  7.56835938e-02, -9.47265625e-02,
       -2.70996094e-02, -2.87109375e-01,  8.39843750e-02,  3.41796875e-01,
        6.44531250e-02,  2.39257812e-02,  1.47460938e-01,  1.66992188e-01,
       -1.04980469e-01, -2.73437500e-01, -1.26953125e-01,  6.29882812e-02,
        3.22265625e-02, -1.98974609e-02, -4.10156250e-02,  1.24023438e-01,
        1.68945312e-01,  

In [15]:
model['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

#### It gives dense matrix means matrix does not zero values or vectors

#### check most similar words

In [18]:
model.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.6272379159927368),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665882110596)]

##### The values are percentage means that word is how much percent closure like glad is closure 74% to happy

In [19]:
model.most_similar('joy')

[('sheer_joy', 0.7729966640472412),
 ('exhilaration', 0.6803831458091736),
 ('elation', 0.6732935309410095),
 ('unbridled_joy', 0.6709332466125488),
 ('joyful', 0.6633967757225037),
 ('delight', 0.6550243496894836),
 ('excitement', 0.6531195044517517),
 ('thrill', 0.6302037239074707),
 ('happiness', 0.6182847023010254),
 ('joyous', 0.6128897666931152)]

In [20]:
model.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819784164429),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.7541396617889404),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.698798656463623)]

In [21]:
model.most_similar('facebook')

[('Facebook', 0.7563533186912537),
 ('FaceBook', 0.7076998353004456),
 ('twitter', 0.6988552212715149),
 ('myspace', 0.6941817998886108),
 ('Twitter', 0.664244532585144),
 ('Facebook.com', 0.6529868245124817),
 ('FacebookFacebook', 0.6162721514701843),
 ('facebook.com', 0.6135972142219543),
 ('Twitter.com', 0.6102107763290405),
 ('TwitterTwitter', 0.6085205674171448)]

In [23]:
model.most_similar('LinkedIn')

[('Linkedin', 0.7829352021217346),
 ('LinkedIn.com', 0.684681236743927),
 ('Facebook_LinkedIn', 0.617587149143219),
 ('Jobster', 0.5929921865463257),
 ('Facebook', 0.5850741863250732),
 ('social_networking', 0.5696631669998169),
 ('Viadeo', 0.5554254651069641),
 ('Xobni', 0.5481542944908142),
 ('SlideShare', 0.5445795655250549),
 ('Quora', 0.5366740226745605)]

In [24]:
model.most_similar('Instagram')

[('Seesmic', 0.6571531295776367),
 ('Flickr', 0.6571182608604431),
 ('FacebookFacebook', 0.6347207427024841),
 ('Posterous', 0.6346838474273682),
 ('Tumblr', 0.6269142627716064),
 ('Friendfeed', 0.6202862858772278),
 ('Brightkite', 0.6198492646217346),
 ('FriendFeed', 0.5989658832550049),
 ('Del.icio.us', 0.5976784229278564),
 ('TwitterTwitter', 0.5914918184280396)]

#### Most_similar gives similar words and its consine similarity score

##### Here we check similarity between two words and it gets cosine similarity score  or  value how much they are similar. cosine similarity score represent how much they are similar in nature

In [27]:
model.similarity('happy' , 'joy')

0.35500747

#### It shows 35% cosine similarity of those two words means it shows cosine similarity score that score indicates how much those words are similar to each other

In [28]:
model.similarity('cricket' , 'python')

0.06333463

In [29]:
model.similarity('man' , 'women')

0.28830528

In [30]:
model.similarity('man' , 'person')

0.53420264

In [33]:
model.similarity('king' , 'Emperor')

0.3758765

In [34]:
model.similarity ('king' , 'Maharaja')

0.36788118

#### We check some vectors by manipulation

In [36]:
vector = model['king'] - model['man'] + model['women']

In [37]:
print(vector)

[-0.33984375  0.06298828 -0.00994873  0.3305664   0.10327148 -0.25854492
  0.19677734 -0.32476807 -0.15917969  0.45752716 -0.39208984 -0.22460938
  0.02929688  0.31982422 -0.0958252  -0.05932617  0.01855469 -0.03945923
  0.01101685  0.33984375  0.10351562  0.14396667 -0.07641602  0.06640625
 -0.10839844 -0.1953125  -0.3564453  -0.02124023 -0.16503906 -0.16247559
 -0.05519104 -0.1003418   0.01464844  0.23449707 -0.26611328 -0.07080078
 -0.26904297 -0.00292969 -0.06738281 -0.02050781  0.04418945 -0.09326172
  0.12304688  0.10626221  0.10290527  0.01660156 -0.10791016 -0.0065918
  0.17578125  0.10028076  0.22363281 -0.05761719 -0.31743622  0.3922119
 -0.35498047 -0.23643494 -0.01074219 -0.01334572 -0.15283203 -0.00793457
  0.08203125  0.09985352  0.003479    0.11608887  0.14550781 -0.125
 -0.11254883  0.2548828  -0.04345703  0.34985352 -0.02880859  0.15966797
  0.07226562  0.17626953  0.15979004 -0.20263672 -0.23864746  0.3400879
  0.17700195  0.15454102 -0.20385742  0.05224609 -0.0522460

#### We check which vectors are of which words

In [41]:
model.most_similar(vector)

[('king', 0.6478992104530334),
 ('queen', 0.5354937314987183),
 ('women', 0.5233659148216248),
 ('kings', 0.5162314176559448),
 ('queens', 0.4995364248752594),
 ('princes', 0.46233272552490234),
 ('monarch', 0.45280298590660095),
 ('monarchy', 0.4293173849582672),
 ('crown_prince', 0.42302510142326355),
 ('concubines', 0.4224807024002075)]

#### Its related royalty

In [46]:
model.most_similar(['India' , 'Maharashtra'])

[('Gujarat', 0.8304893970489502),
 ('Karnataka', 0.8164682984352112),
 ('Andhra_Pradesh', 0.8073914051055908),
 ('Uttar_Pradesh', 0.8018694519996643),
 ('Tamil_Nadu', 0.788735032081604),
 ('Madhya_Pradesh', 0.788065493106842),
 ('West_Bengal', 0.7795268893241882),
 ('Maharastra', 0.7770972847938538),
 ('Haryana', 0.7623180747032166),
 ('Bihar', 0.7620293498039246)]

In [47]:
model.most_similar('Maharashtra')

[('Karnataka', 0.8751190900802612),
 ('Andhra_Pradesh', 0.8629451394081116),
 ('Uttar_Pradesh', 0.8605340719223022),
 ('Gujarat', 0.860462486743927),
 ('Madhya_Pradesh', 0.8439663648605347),
 ('Maharastra', 0.8295568823814392),
 ('Haryana', 0.8272216320037842),
 ('Tamil_Nadu', 0.8174826502799988),
 ('Bihar', 0.7986072301864624),
 ('West_Bengal', 0.7977324724197388)]

In [49]:
vec = model['India'] - model['INR'] + model['USA']

In [53]:
model.most_similar(vec)

[('USA', 0.7006986141204834),
 ('United_States', 0.4908815324306488),
 ('India', 0.4859938621520996),
 ('Canada', 0.4614386558532715),
 ('Great_Britain', 0.4597444236278534),
 ('Australia', 0.4297773838043213),
 ('America', 0.42488184571266174),
 ('United_Sates', 0.4182013273239136),
 ('Britain', 0.4124716818332672),
 ('United_Kingdom', 0.41157448291778564)]